
services:
  db:
    image: postgres:16
    container_name: freelance-db
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: freelance
    volumes:
      - freelance-db-data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  freelance-db-data: